services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  app:
    image: walmart-api-image:latest
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mongo